Gnucash/gnucash-docs

guide/de/Makefile.am
guide/de/ch_bus_ap.xml
guide/de/ch_bus_ar.xml
guide/de/gnucash-guide.xml

I hope this works without rebasing to the last commit

add chapter 13 to gnucash-guide.xml

---

guide/de/ch_oview.xml

some typos and small corrections based on maint

Corr ch oview

---

guide/de/ch_oview.xml
guide/de/index.xml

update chapter oview to latest English version
rebased it to latest maint some minutes ago

Update ch oview

---

README

John Ralls kindly clarified what this should say.

Fix unclear statement re docbook stylesheets in README.

---

help/C/Help_ch_Account-Actions.xml

Bug-397145 - Second change on this bug, as I overlooked issue noted 

---

xmldocs.make

May as well fix while I notice it.

xmldocs.make minor comment typo

---

help/C/Help_ch_Transactions.xml

Add text to Help to explain the Add Reversing Transaction feature and its function.

Bug 781714: Add Reversing Transaction text for Help document

---

guide/de/ch_oview.xml

german:
Bei der Erstellung der russischen Übersetzung, orientiere ich mich teilweise auch an die deutsche Übersetzung, da nicht alle Sätze sich aus der englischen Sprache 1:1 in die russische Sprache übersetzen lassen. Beim Abgleich des ersten Kapitels sind mir einige kleine Tippfehler aufgefallen.

spelling fix (german) - chapter "Overview"

---

guide/C/ch_reports.xml
help/C/Help_ch_Reports.xml

Not ready yet - added for discussion.
Q&A format is unsatisfatory and will be reworked.
Further use cases welcome.

Add Newbie Guide to the TR

---

guide/C/gnc-glossary.xml

Welp. Maybe this one will go the right way

Bug 791169 - Add Reconciliation definition to glossary

---

guide/C/ch_import_business_data.xml

Rewrote chapter 18 Import Business Data, of the guide. Aligned it with bug fixes and improvements submitted in pull [request #452 in gnucash](https://github.com/Gnucash/gnucash/pull/452).

Rewrite of chapter Import Business Data

---

guide/C/ch_basics.xml

Debit and Credit section showing which accounmt types have debit balances and which haave credit balances and the effect of debits and credits on each account type.
Debits and Credits section
Minor fix to missing tag
Double Entry section
Add a reference to the debit and credit section above

Draft Debit and Credits section

---

guide/C/ch_currency.xml
guide/C/ch_dep.xml
guide/C/ch_loans.xml
guide/C/ch_reports.xml
guide/C/ch_txns.xml

... and other places such as "NOTE" or "Warning".

Remove redundant leading words in the admonition blocks

---

help/C/Help_tips-appendix.xml

Also explain why you need F::Q 1.41

Update fq-sources.html: asx source is working again

---

guide/de/ch_reports.xml
guide/de/gnucash-guide.xml

hello 
I translated the first part (Assets & liabilities) in the chapter Reports.

German reports

---

guide/de/CMakeLists.txt
guide/de/Makefile.am

to the CMakeLists.txt and Makefile.am files.

Added the new report "ch_reports.xml"

---

guide/de/ch_import_business_data.xml

Translation into German language
importattribute wurden anhand aktueller gnucash Version übernommen.
Importbeispiele wurden durch Import in gnucash verifiziert

Update ch_import_business_data.xml (Translation into German language)

---

help/C/Help_ch_GUIMenus.xml

* added new menu items
* corrected the order of menu items
* removed duplicate descriptions
* insert <accel>-Tags

Backport of improvements from de/Help_ch_GUIMenus.xml

---

guide/C/ch_invest.xml
guide/de/ch_invest.xml
guide/it/gnucash-guide.xml
guide/pt/ch_invest.xml
guide/ru/ch_invest.xml

Let me know if the PR requires more than just that.

Fixes reference to Security Editor on Help Manual

---

docbook/gnc-docbookx.dtd
help/de/Help_ch_Account-Actions.xml

* Beschreibung des Dialogs "Konto löschen" neu erstellt
* Verwendung von <variablelist> zur Beschreibung von Bedienelementen in Dialogen
* Anstelle von "..." wird &hellip; für die Texte der Schaltflächen eingesetzt
* diverse Rechtschreibfehler korrigiert
* Tabelle der Kontoarten überarbeitet

L10N:de: Weitere Verbesserung von Help_ch_Account-Actions.xml

---

help/de/Help_ch_GUIMenus.xml

* entfernen des Tags `<textobject>` bei `<mediaobject>`
* ersetzen URLs durch ENTITY
* ersetzen "Kontenhierarchie" und "Kontenstruktur" durch Kontenübersicht
* Korrektur weiterer Schreibfehler
[Edit: Tags sichtbar gemacht, ~fellen]

L10N:de: Noch mehr Verbesserung von Help_ch_GUIMenus.xml

---

help/de/Help_ch_GUIMenus.xml

* Accel-Tags ergänzt
* weitere Short-Cuts eingefügt
* Fußnoten geschrieben
* &hellip durch … ersetzt

L10N:de: Immmr mehr Verbesserung von Help_ch_GUIMenus.xml

---

help/de/Help_ch_Account-Actions.xml
help/de/Help_ch_Transactions.xml

* Account-Actions
* Tranactions

L10N:de: Behandlung der ... (drei Punkte) in den Menüeinträgen korrigiert.

---

help/de/Help_ch_Transactions.xml

Diese Verknüpfung erzeugt eine Warnung bei der PDF-Erzeugung:
help/de> make pdf
…
Request for title of element with no title: screenshot
(id="export-transactions-wizard")
…

L10N:de: Entfernen eines xref-Tags auf ein Screenshot- Objekt

---

guide/C/ch_txns.xml

Replace starting balance with opening balance.
Add comma to the numbers over 1000.

Fix ch_txns.xml

---

guide/C/ch_txns.xml

https://github.com/Gnucash/gnucash-docs/pull/190#discussion_r671407584

Add replaceable tag, in guide-ch_txns

---

guide/C/.gitignore
guide/de/.gitignore
guide/it/.gitignore
guide/ja/.gitignore
guide/pt/.gitignore
help/C/.gitignore
help/de/.gitignore
help/it/.gitignore

* {guide,help}/*/.gitignore were deleted completely.
Split from PR #204.

rm  {guide,help}/*/.gitignore

---

help/C/Help_ch_GUIMenus.xml
help/C/Help_ch_GettingHelp.xml
help/de/Help_ch_GUIMenus.xml
help/de/Help_ch_GettingHelp.xml
help/it/gnucash-help.xml
help/pt/Help_ch_GUIMenus.xml
help/pt/Help_ch_GettingHelp.xml

* id="Using-Help"
* id="usage"

Remove some unresolved ID reference from Help-Files

---

docbook/gnc-docbookx.dtd
guide/C/ch_invest.xml

Change some itemizelist to variablelist.
Replace Finance::Quote with &app-fq;.
Unify Savings account name.
Replace CD with certificate of deposit.
Change some example sections to example elements.
Change some orderedlists to procedures.
Change command for Online Quotes.
Fix according to the reviews.
Modify tags to make translation easier.
Added a space between a word and a tag.
Remove extra spaces within inline tags for translation.

Fix and modify ch_invest.xml

---

guide/C/ch_capgain.xml

Unify words and account names.
Fix minor typos and tags.
Add commas to the numbers.
Add some tags.
Fix according to the review comments.

Fix guide ch_capgain.xml

---

manual/C/Help_ch_Account-Actions.xml

The german translation is included in commit 218e284, PR #178.

Bug 797950 Reconcilation docs don't mention automatic credit card payment feature.

---

docbook/gnc-docbookx.dtd
manual/C/CMakeLists.txt
manual/C/Help_ch_Account-Actions.xml
manual/C/Help_ch_Tools_Assistants.xml
manual/C/Help_ch_Transactions.xml
manual/C/ch_Finance-Quote.xml
manual/C/gnucash-help.xml
manual/de/CMakeLists.txt
manual/de/Help_ch_Account-Actions.xml
manual/de/Help_ch_Customize.xml
manual/de/Help_ch_Tools_Assistants.xml
manual/de/Help_ch_Transactions.xml
manual/de/ch_Finance-Quote.xml
manual/de/gnucash-help.xml

* Description of the installation and configuration of F::Q (moved from
Help_ch_Account-Actions-xml).
* Some passages taken from guide/C/ch_invest.xml in PR #192, commit 7e4e560 (Author
usamimikamen-sk)
* adjust some internal references

Chapter "Online-Quotes" created.

---

manual/de/Help_ch_GUIMenus.xml
manual/de/Help_ch_GettingStarted.xml

* Ergänzen von gekürzten Tabellenüberschriften zur besseren Darstellung
im Tabellenverzeichnis.
* Verwenden des Begriffs "Kontenblatt" anstelle von "Kontobuch".

L10n:de GUIMenus, weitere Verbesserungen

---

docbook/gnc-docbookx.dtd
manual/C/ch_Finance-Quote.xml
manual/de/ch_Finance-Quote.xml

F::Q Even more improvements

---

docbook/gnc-locale-C.dtd
docbook/gnc-locale-de.dtd
manual/de/Help_ch_GUIMenus.xml

This is in addition to commit 4855905 from TANIGUCHI Yasuaki.

dtd-docbook: add more translatable GUI elements (menuitems)

---

manual/de/ch_GettingStarted.xml

* sect1
* abstract
* glosslist
* minor fixing

L10N:de: manual, ch_GettingStarted: improvement

---

docbook/gnc-docbookx.dtd
manual/C/ch_Finance-Quote.xml
manual/de/ch_Finance-Quote.xml
manual/de/ch_Tools_Assistants.xml

The content of this section is taken from the [wiki, Online Quotes](https://wiki.gnucash.org/wiki/Online_Quotes)

manual: ch_Finance_Quote, section Helper Scripts

---

manual/C/ch_Finance-Quote.xml
manual/de/ch_Finance-Quote.xml

* Spelling mistake corrected
* Program calls under Windows improved
* The width of the <screen> elements was set exactly to 80px.

manual ch_Finance-Quote: further improvements

---

manual/C/ch_Transactions.xml

Multi-split csv elaboration
